### PR TITLE
Issue 13 scaffold site

### PR DESCRIPTION
**Pull request by swoloszynski**
###  Not ready yet

I haven't finished writing set up and deploy instructions, but you can see what it looks like [here](http://imho.surge.sh/)

### CODE REVIEW

**Comment by swoloszynski** [comment]
Also, please ignore the obnoxious colors, we'll change the entire style to match the mockups and designs

**Comment by btrav** [comment]
Not super important, but in the `install.md` doc, there's a comments:
`$ brew update`
However, that command requires an argument at the end (e.g. brew update rbenv). Do you know what the full line was supposed to be?

**Comment by btrav** [comment]
Who installed Jekyll? This guy!

**Comment by swoloszynski** [comment]
@btrav Nice! Any more issues you solved while installing that I should note in the docs? I updated the brew update command to just be a comment recommending updating whatever brew doctor tells you to update. 

I also added a couple more commands at the end. Can you check that those work for you?

**Pull request merged**
